DROP DATABASE IF EXISTS SWDControl;

CREATE DATABASE SWDControl;
USE SWDControl;

-- DROP TABLE IF EXISTS derechos;
-- CREATE TABLE derechos(

-- );
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
IDUSUARIO INT UNSIGNED AUTO_INCREMENT,
USUARIO VARCHAR(50) NOT NULL,
PASS VARCHAR(20) NOT NULL,
ACTIVO TINYINT(1) DEFAULT 1,
TIEALTA DATETIME DEFAULT NULL,
TIEMODI DATETIME DEFAULT NULL,
USUALTA INT UNSIGNED DEFAULT '0',
USUMODI INT UNSIGNED DEFAULT '0' ,
-- IDDERECHO UNSIGNED UNSIGNED INT DEFAULT (0) FOREIGN KEY REFERENCES () 
PRIMARY KEY (IDUSUARIO)
);
DROP TABLE IF EXISTS empresas;
CREATE TABLE empresas(
IDEMPRESA INT UNSIGNED AUTO_INCREMENT,
EMPRESA VARCHAR(80) NOT NULL,
CORREO VARCHAR(255),
ACTIVO TINYINT(1) DEFAULT 1,
TIEALTA DATETIME DEFAULT NULL,
TIEMODI DATETIME DEFAULT NULL,
USUALTA INT UNSIGNED DEFAULT '0',
USUMODI INT UNSIGNED DEFAULT '0' ,
PRIMARY KEY (IDEMPRESA)
);
DROP TABLE IF EXISTS solicitantes;
CREATE TABLE solicitantes(
IDSOLICITANTE INT UNSIGNED AUTO_INCREMENT,
IDEMPRESA INT UNSIGNED NOT NULL,
ACTIVO TINYINT(1) DEFAULT 1,
EMAIL VARCHAR(255) NOT NULL,
TIEALTA DATETIME DEFAULT NULL,
TIEMODI DATETIME DEFAULT NULL,
USUALTA INT UNSIGNED DEFAULT '0',
USUMODI INT UNSIGNED DEFAULT '0' ,
PRIMARY KEY (IDSOLICITANTE),
FOREIGN KEY (IDEMPRESA) REFERENCES empresas(IDEMPRESA)
);
DROP TABLE IF EXISTS pendientes;
CREATE TABLE pendientes(
    IDPENDIENTE INT UNSIGNED AUTO_INCREMENT,
    IDUSUARIO INT UNSIGNED NOT NULL,
    TIPOPENDIENTE INT UNSIGNED NOT NULL DEFAULT 1,
    FECHAINI DATETIME NULL,
    FECHAFIN DATETIME NULL,
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0' ,
    PRIMARY KEY (IDPENDIENTE),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);
DROP TABLE IF EXISTS pendientesdetalle;
CREATE TABLE pendientesdetalle(
    IDPENDIENTEDETALLE INT UNSIGNED AUTO_INCREMENT,
    IDPENDIENTE INT UNSIGNED,
    DESCRIPCION VARCHAR(5000),
    EMPRESA VARCHAR(255),
    ETIQUETA VARCHAR(255),
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0' ,
    PRIMARY KEY (IDPENDIENTEDETALLE),
    FOREIGN KEY (IDPENDIENTE) REFERENCES pendientes(IDPENDIENTE)
);
DROP TABLE IF EXISTS cuentas;
CREATE TABLE cuentas(
    IDCUENTA INT UNSIGNED AUTO_INCREMENT,
    CUENTA VARCHAR(255) NOT NULL,
    HOST VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASS VARCHAR(255) NOT NULL,
    PORT VARCHAR(255) NOT NULL,
    ACTIVO TINYINT(1) DEFAULT '1',
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0' ,
    PRIMARY KEY (IDCUENTA)
);
DROP TABLE IF EXISTS plantillas;
CREATE TABLE plantillas(
    IDPLANTILLA INT UNSIGNED AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    CONTENIDO BLOB,
    IDUSUARIO INT UNSIGNED,
    ACTIVO TINYINT(1) DEFAULT '1',
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0' ,
    PRIMARY KEY (IDPLANTILLA),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO)
);
DROP TABLE IF EXISTS apps;
CREATE TABLE apps(
    IDAPP INT UNSIGNED AUTO_INCREMENT,
    APP VARCHAR(255) NOT NULL,
    ACTIVO TINYINT(1) DEFAULT '1',
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0',
    PRIMARY KEY(IDAPP)
);
DROP TABLE IF EXISTS reportes;
CREATE TABLE reportes(
    IDREPORTE INT UNSIGNED AUTO_INCREMENT,
    URGENCIA INT UNSIGNED,
    CC VARCHAR(200) DEFAULT NULL,
    ETIQUETAS VARCHAR(200) DEFAULT NULL,
    TIPO INT UNSIGNED,
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0' ,
    IDAPP INT UNSIGNED,
    IDUSUARIO INT UNSIGNED,
    IDSOLICITANTE INT UNSIGNED,
    PRIMARY KEY (IDREPORTE),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS(IDUSUARIO),
    FOREIGN KEY (IDSOLICITANTE) REFERENCES SOLICITANTES(IDSOLICITANTE),
    FOREIGN KEY (IDAPP) REFERENCES APPS(IDAPP)
);
DROP TABLE IF EXISTS reportesdetalle;
CREATE TABLE reportesdetalle(
    IDREPORTEDETALLE INT UNSIGNED AUTO_INCREMENT,
    IDREPORTE INT UNSIGNED,
    REPORTE BLOB,
    NOTAINTERNA BLOB,
    ASUNTO VARCHAR (255) NOT NULL,
    TIEALTA DATETIME DEFAULT NULL,
    TIEMODI DATETIME DEFAULT NULL,
    USUALTA INT UNSIGNED DEFAULT '0',
    USUMODI INT UNSIGNED DEFAULT '0',
    PRIMARY KEY (IDREPORTEDETALLE),
    FOREIGN KEY (IDREPORTE) REFERENCES reportes(IDREPORTE)
);


------------------------FUNCIONES------------------
-- DROP FUNCTION LOGIN;
-- DELIMITER //
-- CREATE FUNCTION login(USUARIO VARCHAR(50),CONTRA VARCHAR(20)) RETURNS int DETERMINISTIC
--     BEGIN
--         DECLARE IDUSU INT;
--         SELECT idusuario INTO IDUSU FROM usuarios t WHERE USUARIO=T.USUARIO AND PASS=CONTRA;
--         IF IDUSU IS NULL THEN 
--            SET IDUSU=-1;
--         END IF;
--        RETURN IDUSU;
--     END//
-- DELIMITER ;
-- SELECT login('admin','adminA');
-- SELECT idusuario FROM usuarios t WHERE USUARIO='ADNMIN' AND PASS='ADMIN';
------------------------Procedimientos almacenados------------------
------------------------INSERTS------------------
INSERT INTO USUARIOS(usuario,pass,activo) VALUES ('ADMIN',"Admin",1);

INSERT INTO pendientes(IDUSUARIO,TIPOPENDIENTE,FECHAINI) VALUES (1,1,NOW());
INSERT INTO pendientes(IDUSUARIO,TIPOPENDIENTE,FECHAINI) VALUES (1,2,NOW());
INSERT INTO pendientes(IDUSUARIO,TIPOPENDIENTE,FECHAINI) VALUES (1,3,NOW());